### ISSUE TITLE
Crash with current code

### ISSUE THREAD

**Issue by ronaaron** [mcindrich/chtml#1]
Hello, I was interested in a minimal HTML parser, so I took a look at yours.

Compiled under macOS (though 'main.c' didn't exist so I took from the web page).

Running 'bin/chtml test/test.html' gives me:

Root element: 
         name -> html
         content -> (null)
Segmentation fault: 11

**Comment by zinccyy** [comment]
Sorry I'm late, I just saw this issue. Can you please post all the files where the code crashes ( html + main.c ).

**Comment by zinccyy** [comment]
If the main.c was created as an example from the README.md and the html file was test.html, the issue is that the root element doesen't have any attributes and then the seg fault occurs. The code in README was just an example for accessing all parameters of html elements.
